In [1]:
list=[1,2,3,4,5]
### append
list.append(6)
print(list)

[1, 2, 3, 4, 5, 6]


In [3]:
### extend
list.extend([7,8]) 
print(list)

[1, 2, 3, 4, 5, 6, 7, 8]


In [4]:
### insert 
list.insert(2,9) 
print(list)

[1, 2, 9, 3, 4, 5, 6, 7, 8]


In [5]:
### remove 
list.remove(9) 
print(list)

[1, 2, 3, 4, 5, 6, 7, 8]


In [7]:
### pop 
list.pop() 
print(list)
list.pop(1) 
print(list)

[1, 2, 3, 4, 5, 6]
[1, 3, 4, 5, 6]


In [8]:
### clear 
list.clear() 
print(list)

[]


In [13]:
list=[1,2,2,3,4,5] 
### index 
pos=list.index(4)
print(pos)

4


In [14]:
### count 
count=list.count(2) 
print(count)

2


In [15]:
### sort
list=[5,2,3,1,4] 
list.sort() 
print(list)

[1, 2, 3, 4, 5]


In [16]:
### reverse 
list.reverse() 
print(list)

[5, 4, 3, 2, 1]


In [ ]:
# append ---- add one element at once 
# extend -----add multiple elements at a time 
# insert -----add a element at particular position
# remove -----delete by value 
# pop    -----delete by index 
# clear  -----deletes all elements from the list 
# index  -----find position of a element 
# count  -----counting number of occurance of a element 
# sort   -----sorting in order wise (ascending or descending) 
# reverse----- reverse the list

In [17]:
### creating a tuple with 3 student names 
students=('Ram','Rajesh','Rahul')
print(students)

('Ram', 'Rajesh', 'Rahul')


In [18]:
### changing the second student name in tuple 
students[1]='Ravan'

TypeError: 'tuple' object does not support item assignment

In [20]:
### creates a set with duplicate values 
set={10,20,30,10,40,20,50}
### printing of set elements
print(set)

{50, 20, 40, 10, 30}


In [23]:
### creates a new dictionary with keys name ,age , city 
dict={'name':'rakesh',
      'age': 21 ,
      'city': 'Pune'} 
print("printing original dictionary",dict)

printing original dictionary {'name': 'rakesh', 'age': 21, 'city': 'Pune'}


In [24]:
### updating the age 
dict['age']=22 
print("printing dict after age update",dict)

printing dict after age update {'name': 'rakesh', 'age': 22, 'city': 'Pune'}


In [25]:
### adding new key email 
dict['email']='rakesh@gmail.com' 
print("printing dict after adding new key email",dict)

printing dict after adding new key email {'name': 'rakesh', 'age': 22, 'city': 'Pune', 'email': 'rakesh@gmail.com'}


In [26]:
### final dictionary 
print(dict)

{'name': 'rakesh', 'age': 22, 'city': 'Pune', 'email': 'rakesh@gmail.com'}


In [29]:
### script for checking age eligibility for vote 
def Vote(n):
    if n>=18:
        return "You can Vote"
    else:
        return " Your Not Eligible for Vote"
n=int(input("enter your age:"))
print(Vote(n))


enter your age: 21


You can Vote


In [34]:
### script for Grade 
def Grade(marks):
    if marks>=90:
        return "A"
    elif 75<marks<89:
        return "B" 
    elif 50<marks<74:
        return "C" 
    else:
        return "Fail" 
marks=int(input("enter marks:"))
print(Grade(marks))

enter marks: 76


B


In [37]:
### scrip for positive or negative number 
def Sign(n):
    if n>0: 
        return 'positive' 
    elif n<0: 
        return 'negative' 
    else:
        return 'zero' 
n=int(input("enter number:"))
print(Sign(n))

enter number: 1


positive


In [39]:
#### importing numpy package for creating a numpy array
import numpy as np 
### creates a scaler array 
scaler=np.array(5) 
scaler

array(5)

In [40]:
#### 1D array with values 1 to 5 
array=np.array([1,2,3,4,5]) 
array

array([1, 2, 3, 4, 5])

In [42]:
### creating 2D array with 2 rows and 3 columns and values from 10 to 60 in step of 10 
array2D=np.array([[10,20,30],[40,50,60]])
### printing 2D array elements
array2D

array([[10, 20, 30],
       [40, 50, 60]])

In [43]:
### creating random 4*4  numpy array  between 0 to 100 
nump_array=np.random.randint(0,101,size=(4,4))

In [44]:
#### printing 4*4 numpy array after generates 
nump_array

array([[28, 93, 43,  0],
       [87,  3, 93, 47],
       [ 1, 99, 36, 55],
       [41, 10, 44, 96]], dtype=int32)

In [47]:
### creating a numpy array(3*3) 
array=np.array([[10,20,30],[40,50,60],[70,80,90]])
### 3*3 numpy array elements 
array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [48]:
### converting 2D array into dataframe we need pandas library 
### imports pandas  
import pandas as pd

In [49]:
### convert 2D numpy array to dataframe
df=pd.DataFrame(array,columns=['A','B','C'])

In [50]:
### printing dataframe 
df

,A,B,C
0,10,20,30
1,40,50,60
2,70,80,90


In [51]:
#### to exploring pandas pandas package should be import
import pandas as pd

In [69]:
### creating a small dataframe with rows and 4 columns
### create a dictionary
data = {
    "Name": ["Rakesh", "Anita", "Vijay", "Sneha", "Arjun", 
             "Rakesh", "Meera", "Kiran", "Priya", "Rahul"],
    "Age": [25, 30, 28, 22, 35, 25, 29, 31, 26, 24],
    "City": ["Bengaluru", "Delhi", "Mumbai", "Chennai", "Hyderabad", 
             "Bengaluru", "Pune", "Kolkata", "Jaipur", "Goa"],
    "Salary": [50000, 60000, np.nan, 45000, 70000, 50000, 55000, 62000, np.nan, 48000]
}

In [70]:
#### convert dict into dataframe 
df=pd.DataFrame(data)

In [71]:
df

,Name,Age,City,Salary
0,Rakesh,25,Bengaluru,50000.0
1,Anita,30,Delhi,60000.0
2,Vijay,28,Mumbai,NaN
3,Sneha,22,Chennai,45000.0
4,Arjun,35,Hyderabad,70000.0
5,Rakesh,25,Bengaluru,50000.0
6,Meera,29,Pune,55000.0
7,Kiran,31,Kolkata,62000.0
8,Priya,26,Jaipur,NaN
9,Rahul,24,Goa,48000.0


In [72]:
### info() 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [73]:
#### describe() 
df.describe()

,Age,Salary
count,10.000000,8.000000
mean,27.500000,55000.000000
std,3.865805,8434.622525
min,22.000000,45000.000000
25%,25.000000,49500.000000
50%,27.000000,52500.000000
75%,29.750000,60500.000000
max,35.000000,70000.000000


In [74]:
### selecting name and city columns
df[['Name','City']]

,Name,City
0,Rakesh,Bengaluru
1,Anita,Delhi
2,Vijay,Mumbai
3,Sneha,Chennai
4,Arjun,Hyderabad
5,Rakesh,Bengaluru
6,Meera,Pune
7,Kiran,Kolkata
8,Priya,Jaipur
9,Rahul,Goa


In [75]:
### drop the city column 
df=df.drop(columns=['City'],axis=1)

In [76]:
df

,Name,Age,Salary
0,Rakesh,25,50000.0
1,Anita,30,60000.0
2,Vijay,28,NaN
3,Sneha,22,45000.0
4,Arjun,35,70000.0
5,Rakesh,25,50000.0
6,Meera,29,55000.0
7,Kiran,31,62000.0
8,Priya,26,NaN
9,Rahul,24,48000.0


In [82]:
### missing values 
df.isnull().sum()

Name      0
Age       0
Salary    2
dtype: int64

In [87]:
### filling the missing values respected value
df.fillna({'Salary':df['Salary'].median()},inplace=True)

In [88]:
df.isnull().sum()

Name      0
Age       0
Salary    0
dtype: int64

In [89]:
#### duplicates finding 
df.duplicated().sum()

np.int64(1)

In [90]:
#### remove duplicates rows 
df.drop_duplicates(inplace=True,ignore_index=True)

In [92]:
df.duplicated().sum()

np.int64(0)